# Generated by Django 5.0.6 on 2024-05-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
